# KTLYST - Block phishing domains via Exchange Online transport rule
# Generated: 2026-04-09
# Review before running. This blocks inbound email containing these domains.
#
# Prerequisites:
#   Connect-ExchangeOnline -UserPrincipalName admin@yourdomain.com

$domains = @('www.propublica.org', 'www.theregister.com', 'www.pcgamer.com', 'michelf.ca')

New-TransportRule `
    -Name "KTLYST - Block Device Code Phishing Domains (2026-04-09)" `
    -SubjectOrBodyContainsWords $domains `
    -FromAddressContainsWords $domains `
    -SenderDomainIs $domains `
    -DeleteMessage $true `
    -Comments "Auto-generated by KTLYST from Unit42 device code phishing advisory."

# To also block in URLs within message bodies:
# New-TransportRule `
#     -Name "KTLYST - Block Phishing URLs (2026-04-09)" `
#     -HeaderContainsMessageHeader "X-MS-Exchange-Organization-UrlScan-Verdict" `
#     -SubjectOrBodyContainsWords $domains `
#     -DeleteMessage $true
