<#
.SYNOPSIS
    Hunt for TeamPCP/Trivy supply chain persistence artifacts on developer machines.

.DESCRIPTION
    Scans for the sysmon.py systemd user service persistence mechanism deployed
    by the Trivy v0.69.4 supply chain compromise (March 19-23, 2026).
    Checks for C2 polling to tdtqy-oyaaa-aaaae-af2dq-cai.raw.icp0.io.

.NOTES
    Source: Wiz Research - Trivy/TeamPCP Supply Chain Attack
    Generated by KTLYST Security Learning Control Plane
#>

param(
    [string[]]$ComputerName = @($env:COMPUTERNAME),
    [switch]$RemoteScan,
    [string]$OutputPath = ".\trivy_persistence_hunt_results.csv"
)

$findings = @()
$c2Domains = @(
    "scan.aquasecurtiy.org",
    "tdtqy-oyaaa-aaaae-af2dq-cai.raw.icp0.io",
    "plug-tab-protective-relay.trycloudflare.com"
)

function Test-Persistence {
    param([string]$Computer)

    $result = [PSCustomObject]@{
        Hostname        = $Computer
        ScanTime        = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        SysmonPyFound   = $false
        SysmonPyPath    = ""
        SysmonPyContent = ""
        C2Polling       = $false
        C2Connections   = ""
        TmpPglogFound   = $false
        TpcpTarFound    = $false
        SystemdServices = ""
        Status          = "Clean"
    }

    # --- Check 1: sysmon.py persistence file ---
    $persistencePaths = @(
        "$env:USERPROFILE\.config\systemd\user\sysmon.py",
        "$env:HOME/.config/systemd/user/sysmon.py",
        "/home/*/.config/systemd/user/sysmon.py"
    )

    foreach ($path in $persistencePaths) {
        $expanded = Resolve-Path -Path $path -ErrorAction SilentlyContinue
        if ($expanded) {
            foreach ($match in $expanded) {
                if (Test-Path $match.Path) {
                    $result.SysmonPyFound = $true
                    $result.SysmonPyPath = $match.Path
                    $result.Status = "COMPROMISED"
                    try {
                        $content = Get-Content $match.Path -Raw -ErrorAction SilentlyContinue
                        $result.SysmonPyContent = $content.Substring(0, [Math]::Min(500, $content.Length))
                    } catch {}
                    Write-Warning "[!] FOUND persistence file: $($match.Path) on $Computer"
                }
            }
        }
    }

    # --- Check 2: Active DNS/network connections to C2 ---
    try {
        $dnsCache = Get-DnsClientCache -ErrorAction SilentlyContinue
        foreach ($domain in $c2Domains) {
            $c2Hit = $dnsCache | Where-Object { $_.Entry -like "*$domain*" }
            if ($c2Hit) {
                $result.C2Polling = $true
                $result.C2Connections += "$domain (DNS cache); "
                $result.Status = "COMPROMISED"
                Write-Warning "[!] C2 domain found in DNS cache: $domain on $Computer"
            }
        }
    } catch {
        Write-Verbose "DNS cache check not available on $Computer"
    }

    # --- Check 3: Active network connections to C2 IP ---
    try {
        $netConns = Get-NetTCPConnection -ErrorAction SilentlyContinue |
            Where-Object { $_.RemoteAddress -eq "45.148.10.212" }
        if ($netConns) {
            $result.C2Polling = $true
            $result.C2Connections += "45.148.10.212 (active TCP); "
            $result.Status = "COMPROMISED"
            Write-Warning "[!] Active connection to C2 IP 45.148.10.212 on $Computer"
        }
    } catch {}

    # --- Check 4: Dropper artifacts ---
    if (Test-Path "/tmp/pglog" -ErrorAction SilentlyContinue) {
        $result.TmpPglogFound = $true
        $result.Status = "COMPROMISED"
        Write-Warning "[!] Dropper artifact /tmp/pglog found on $Computer"
    }

    # --- Check 5: Encrypted credential bundle ---
    $tpcpPaths = @("/tmp/tpcp.tar.gz", "$env:TEMP\tpcp.tar.gz")
    foreach ($tp in $tpcpPaths) {
        if (Test-Path $tp -ErrorAction SilentlyContinue) {
            $result.TpcpTarFound = $true
            $result.Status = "COMPROMISED"
            Write-Warning "[!] Credential bundle tpcp.tar.gz found at $tp on $Computer"
        }
    }

    # --- Check 6: Systemd user services (Linux/WSL) ---
    $systemdUserDir = "$env:HOME/.config/systemd/user/"
    if (Test-Path $systemdUserDir -ErrorAction SilentlyContinue) {
        $services = Get-ChildItem $systemdUserDir -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty Name
        $result.SystemdServices = ($services -join ", ")
    }

    return $result
}

Write-Host "`n=== TeamPCP/Trivy Persistence Hunter ===" -ForegroundColor Cyan
Write-Host "Scanning for supply chain compromise artifacts (March 2026)`n"

foreach ($computer in $ComputerName) {
    Write-Host "Scanning: $computer ..." -ForegroundColor Yellow
    if ($RemoteScan -and $computer -ne $env:COMPUTERNAME) {
        try {
            $result = Invoke-Command -ComputerName $computer -ScriptBlock ${function:Test-Persistence} -ArgumentList $computer
        } catch {
            Write-Warning "Failed to connect to $computer : $_"
            continue
        }
    } else {
        $result = Test-Persistence -Computer $computer
    }
    $findings += $result
}

# Output summary
Write-Host "`n=== Scan Results ===" -ForegroundColor Cyan
$compromised = $findings | Where-Object { $_.Status -eq "COMPROMISED" }
$clean = $findings | Where-Object { $_.Status -eq "Clean" }

Write-Host "Scanned: $($findings.Count) hosts"
Write-Host "Clean:   $($clean.Count)" -ForegroundColor Green
if ($compromised.Count -gt 0) {
    Write-Host "COMPROMISED: $($compromised.Count)" -ForegroundColor Red
    Write-Host "`nCompromised hosts:" -ForegroundColor Red
    $compromised | ForEach-Object {
        Write-Host "  - $($_.Hostname): sysmon.py=$($_.SysmonPyFound), C2=$($_.C2Polling), pglog=$($_.TmpPglogFound)" -ForegroundColor Red
    }
}

# Export results
$findings | Export-Csv -Path $OutputPath -NoTypeInformation
Write-Host "`nResults exported to: $OutputPath"
