#!/usr/bin/env bash
#
# trivy_version_audit.sh - Audit Trivy installations for compromised versions
#
# Checks for Trivy v0.69.4 binaries (by hash) and compromised Docker images
# (0.69.4, 0.69.5, 0.69.6) across local systems and container registries.
#
# Source: Wiz Research - Trivy/TeamPCP Supply Chain Attack (March 2026)
# Generated by KTLYST Security Learning Control Plane

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Known malicious hashes for Trivy v0.69.4
declare -A MALICIOUS_HASHES=(
    ["887e1f5b5b50162a60bd03b66269e0ae545d0aef0583c1c5b00972152ad7e073"]="FreeBSD-64bit"
    ["f7084b0229dce605ccc5506b14acd4d954a496da4b6134a294844ca8d601970d"]="Linux-32bit"
    ["822dd269ec10459572dfaaefe163dae693c344249a0161953f0d5cdd110bd2a0"]="Linux-64bit"
    ["bef7e2c5a92c4fa4af17791efc1e46311c0f304796f1172fce192f5efc40f5d7"]="Linux-ARM"
    ["e64e152afe2c722d750f10259626f357cdea40420c5eedae37969fbf13abbecf"]="Linux-ARM64"
    ["ecce7ae5ffc9f57bb70efd3ea136a2923f701334a8cd47d4fbf01a97fd22859c"]="Linux-PPC64LE"
    ["d5edd791021b966fb6af0ace09319ace7b97d6642363ef27b3d5056ca654a94c"]="Linux-s390x"
    ["e6310d8a003d7ac101a6b1cd39ff6c6a88584c815d937910f1ddd538"]="macOS-64bit"
    ["6328a34b26a63423b555a61f89a6a0525a534e9c88584c815d937910f1ddd538"]="macOS-ARM64"
    ["0880819ef821cff918960a39c1c1aada55a5593c61c608ea9215da858a86e349"]="Windows-64bit"
)

COMPROMISED_TAGS=("0.69.4" "0.69.5" "0.69.6")
FINDINGS=0

echo -e "${CYAN}=== Trivy Version Audit ===${NC}"
echo "Scanning for compromised Trivy v0.69.4 binaries and Docker images"
echo "Reference: Trivy/TeamPCP Supply Chain Attack (March 19-23, 2026)"
echo ""

# --- Check 1: Local Trivy binary ---
echo -e "${CYAN}[1/4] Checking local Trivy installations...${NC}"

TRIVY_PATHS=$(which -a trivy 2>/dev/null || true)
if [ -n "$TRIVY_PATHS" ]; then
    while IFS= read -r trivy_path; do
        echo "  Found: $trivy_path"

        # Check version
        version=$("$trivy_path" version 2>/dev/null | grep -oP 'Version:\s+\K.*' || "$trivy_path" --version 2>/dev/null | grep -oP '\d+\.\d+\.\d+' || echo "unknown")
        echo "  Version: $version"

        if [[ "$version" == *"0.69.4"* ]] || [[ "$version" == *"0.69.5"* ]] || [[ "$version" == *"0.69.6"* ]]; then
            echo -e "  ${RED}[!] COMPROMISED VERSION DETECTED: $version${NC}"
            FINDINGS=$((FINDINGS + 1))
        fi

        # Check hash
        hash=$(sha256sum "$trivy_path" 2>/dev/null | awk '{print $1}' || shasum -a 256 "$trivy_path" 2>/dev/null | awk '{print $1}' || echo "")
        if [ -n "$hash" ]; then
            echo "  SHA-256: $hash"
            if [[ -v "MALICIOUS_HASHES[$hash]" ]]; then
                echo -e "  ${RED}[!] MALICIOUS HASH MATCH: ${MALICIOUS_HASHES[$hash]}${NC}"
                FINDINGS=$((FINDINGS + 1))
            else
                echo -e "  ${GREEN}  Hash not in known-bad list${NC}"
            fi
        fi
        echo ""
    done <<< "$TRIVY_PATHS"
else
    echo -e "  ${GREEN}No local Trivy binary found in PATH${NC}"
    echo ""
fi

# --- Check 2: Docker images ---
echo -e "${CYAN}[2/4] Checking local Docker images...${NC}"

if command -v docker &>/dev/null; then
    for tag in "${COMPROMISED_TAGS[@]}"; do
        for image in "aquasec/trivy:$tag" "ghcr.io/aquasecurity/trivy:$tag"; do
            found=$(docker images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -F "$image" || true)
            if [ -n "$found" ]; then
                echo -e "  ${RED}[!] COMPROMISED IMAGE FOUND: $found${NC}"
                echo "      Action: Remove immediately with 'docker rmi $found'"
                FINDINGS=$((FINDINGS + 1))
            fi
        done
    done

    # Check running containers
    running=$(docker ps --format '{{.Image}}' 2>/dev/null | grep -E "trivy.*(0\.69\.[456])" || true)
    if [ -n "$running" ]; then
        echo -e "  ${RED}[!] COMPROMISED TRIVY CONTAINER RUNNING:${NC}"
        echo "      $running"
        FINDINGS=$((FINDINGS + 1))
    fi

    if [ $FINDINGS -eq 0 ]; then
        echo -e "  ${GREEN}No compromised Docker images found locally${NC}"
    fi
else
    echo -e "  ${YELLOW}Docker not available - skipping local image check${NC}"
fi
echo ""

# --- Check 3: GitHub Actions cache ---
echo -e "${CYAN}[3/4] Checking for cached Trivy binaries...${NC}"

CACHE_PATHS=(
    "$HOME/.cache/trivy"
    "$HOME/.trivy"
    "/tmp/trivy-cache"
    "/var/lib/trivy"
)

for cache_dir in "${CACHE_PATHS[@]}"; do
    if [ -d "$cache_dir" ]; then
        echo "  Checking: $cache_dir"
        find "$cache_dir" -type f -executable 2>/dev/null | while read -r binary; do
            hash=$(sha256sum "$binary" 2>/dev/null | awk '{print $1}' || shasum -a 256 "$binary" 2>/dev/null | awk '{print $1}' || echo "")
            if [ -n "$hash" ] && [[ -v "MALICIOUS_HASHES[$hash]" ]]; then
                echo -e "  ${RED}[!] MALICIOUS BINARY IN CACHE: $binary (${MALICIOUS_HASHES[$hash]})${NC}"
                FINDINGS=$((FINDINGS + 1))
            fi
        done
    fi
done
echo ""

# --- Check 4: Persistence artifacts ---
echo -e "${CYAN}[4/4] Checking for persistence artifacts...${NC}"

PERSISTENCE_FILE="$HOME/.config/systemd/user/sysmon.py"
if [ -f "$PERSISTENCE_FILE" ]; then
    echo -e "  ${RED}[!] PERSISTENCE FILE FOUND: $PERSISTENCE_FILE${NC}"
    echo "      This system has the TeamPCP backdoor installed."
    echo "      The file polls tdtqy-oyaaa-aaaae-af2dq-cai.raw.icp0.io every 5 minutes."
    echo "      Action: Remove file, rotate ALL credentials, investigate lateral movement."
    FINDINGS=$((FINDINGS + 1))
else
    echo -e "  ${GREEN}No sysmon.py persistence found${NC}"
fi

if [ -f "/tmp/pglog" ]; then
    echo -e "  ${RED}[!] DROPPER ARTIFACT FOUND: /tmp/pglog${NC}"
    FINDINGS=$((FINDINGS + 1))
fi
echo ""

# --- Summary ---
echo -e "${CYAN}=== Audit Summary ===${NC}"
if [ $FINDINGS -gt 0 ]; then
    echo -e "${RED}FINDINGS: $FINDINGS indicators of compromise detected${NC}"
    echo ""
    echo "Immediate actions:"
    echo "  1. Quarantine affected systems"
    echo "  2. Rotate ALL credentials accessible from affected CI/CD pipelines"
    echo "  3. Revoke GitHub tokens, PATs, and deploy keys from the attack window"
    echo "  4. Check for tpcp-docs repos in your GitHub org"
    echo "  5. Review AWS/GCP/Azure secrets access logs (March 19-23, 2026)"
else
    echo -e "${GREEN}No indicators of compromise found${NC}"
    echo "  Trivy installations appear clean of TeamPCP supply chain compromise."
fi
