# KTLYST - Block phishing domains via Exchange Online transport rule
# Generated: 2026-04-12
# Organization: NYS Office of Information Technology Services
# Review before running. This blocks inbound email containing these domains.
#
# Prerequisites:
#   Connect-ExchangeOnline -UserPrincipalName admin@yourdomain.com

$domains = @('iconicsinc.my.site.com', 'www.mitsubishielectric.co.jp', 'iconics.com')

New-TransportRule `
    -Name "NYS Office of Information Technology Services - KTLYST Block Phishing Domains (2026-04-12)" `
    -SubjectOrBodyContainsWords $domains `
    -FromAddressContainsWords $domains `
    -SenderDomainIs $domains `
    -DeleteMessage $true `
    -Comments "Auto-generated by KTLYST for NYS Office of Information Technology Services."

# To also block in URLs within message bodies:
# New-TransportRule `
#     -Name "NYS Office of Information Technology Services - KTLYST Block Phishing URLs (2026-04-12)" `
#     -HeaderContainsMessageHeader "X-MS-Exchange-Organization-UrlScan-Verdict" `
#     -SubjectOrBodyContainsWords $domains `
#     -DeleteMessage $true
