#!/usr/bin/env python3
"""
aws_secrets_audit.py - Audit AWS Secrets Manager access during Trivy/TeamPCP attack window.

The TeamPCP malware harvested cloud credentials from CI/CD environments.
This script checks AWS CloudTrail and Secrets Manager access logs for
unauthorized access during March 19-23, 2026.

Source: Wiz Research - Trivy/TeamPCP Supply Chain Attack
Generated by KTLYST Security Learning Control Plane
"""

import json
import sys
from datetime import datetime, timezone

try:
    import boto3
    from botocore.exceptions import ClientError, NoCredentialsError
except ImportError:
    print("ERROR: boto3 is required. Install with: pip install boto3")
    sys.exit(1)

ATTACK_WINDOW_START = datetime(2026, 3, 19, 0, 0, 0, tzinfo=timezone.utc)
ATTACK_WINDOW_END = datetime(2026, 3, 24, 0, 0, 0, tzinfo=timezone.utc)

# Known malicious indicators
C2_IPS = {"45.148.10.212"}
SUSPICIOUS_USER_AGENTS = {"python-requests", "curl", "wget", "Go-http-client"}


def audit_cloudtrail_secrets_access(region: str = "us-east-1") -> list[dict]:
    """Query CloudTrail for Secrets Manager access during the attack window."""
    findings = []

    try:
        ct_client = boto3.client("cloudtrail", region_name=region)
    except NoCredentialsError:
        print(f"  [!] No AWS credentials configured for region {region}")
        return findings

    print(f"  Querying CloudTrail in {region}...")

    secret_events = [
        "GetSecretValue",
        "DescribeSecret",
        "ListSecrets",
        "BatchGetSecretValue",
    ]

    for event_name in secret_events:
        try:
            paginator = ct_client.get_paginator("lookup_events")
            page_iterator = paginator.paginate(
                LookupAttributes=[
                    {"AttributeKey": "EventName", "AttributeValue": event_name}
                ],
                StartTime=ATTACK_WINDOW_START,
                EndTime=ATTACK_WINDOW_END,
                MaxResults=50,
            )

            for page in page_iterator:
                for event in page.get("Events", []):
                    event_data = json.loads(event.get("CloudTrailEvent", "{}"))
                    source_ip = event_data.get("sourceIPAddress", "unknown")
                    user_agent = event_data.get("userAgent", "unknown")
                    user_identity = event_data.get("userIdentity", {})
                    principal = user_identity.get("arn", user_identity.get("type", "unknown"))

                    finding = {
                        "timestamp": event["EventTime"].isoformat(),
                        "event": event_name,
                        "source_ip": source_ip,
                        "user_agent": user_agent,
                        "principal": principal,
                        "resource": event_data.get("requestParameters", {}).get("secretId", "N/A"),
                        "region": region,
                        "risk": "low",
                        "reason": "",
                    }

                    # Flag high-risk indicators
                    if source_ip in C2_IPS:
                        finding["risk"] = "critical"
                        finding["reason"] = f"Access from known TeamPCP C2 IP: {source_ip}"
                    elif any(ua in user_agent.lower() for ua in SUSPICIOUS_USER_AGENTS):
                        finding["risk"] = "medium"
                        finding["reason"] = f"Suspicious user agent: {user_agent}"
                    elif "assumed-role" in principal.lower() and "github" in principal.lower():
                        finding["risk"] = "high"
                        finding["reason"] = "GitHub Actions assumed role during attack window"
                    elif "ci" in principal.lower() or "build" in principal.lower():
                        finding["risk"] = "high"
                        finding["reason"] = "CI/CD service account access during attack window"

                    findings.append(finding)

        except ClientError as e:
            print(f"  [!] CloudTrail error for {event_name}: {e}")

    return findings


def audit_iam_access_keys(region: str = "us-east-1") -> list[dict]:
    """Check for IAM access keys used during the attack window."""
    findings = []

    try:
        iam_client = boto3.client("iam", region_name=region)
    except NoCredentialsError:
        return findings

    print("  Checking IAM access keys last used during attack window...")

    try:
        paginator = iam_client.get_paginator("list_users")
        for page in paginator.paginate():
            for user in page["Users"]:
                keys = iam_client.list_access_keys(UserName=user["UserName"])
                for key in keys["AccessKeyMetadata"]:
                    if key["Status"] != "Active":
                        continue
                    try:
                        last_used = iam_client.get_access_key_last_used(
                            AccessKeyId=key["AccessKeyId"]
                        )
                        used_date = last_used["AccessKeyLastUsed"].get("LastUsedDate")
                        if used_date and ATTACK_WINDOW_START <= used_date <= ATTACK_WINDOW_END:
                            findings.append({
                                "type": "iam_key_used",
                                "user": user["UserName"],
                                "key_id": key["AccessKeyId"],
                                "last_used": used_date.isoformat(),
                                "service": last_used["AccessKeyLastUsed"].get("ServiceName", "unknown"),
                                "region": last_used["AccessKeyLastUsed"].get("Region", "unknown"),
                                "risk": "medium",
                                "reason": "Access key used during attack window",
                            })
                    except ClientError:
                        pass
    except ClientError as e:
        print(f"  [!] IAM error: {e}")

    return findings


def main():
    print("=" * 60)
    print("AWS Secrets Audit - Trivy/TeamPCP Attack Window")
    print(f"Window: {ATTACK_WINDOW_START.date()} to {ATTACK_WINDOW_END.date()}")
    print("=" * 60)
    print()

    regions = ["us-east-1", "us-west-2", "eu-west-1", "eu-central-1"]
    all_findings = []

    # Audit CloudTrail for secrets access
    print("[1/2] Auditing CloudTrail for Secrets Manager access...")
    for region in regions:
        findings = audit_cloudtrail_secrets_access(region)
        all_findings.extend(findings)
    print(f"  Found {len(all_findings)} Secrets Manager access events")
    print()

    # Audit IAM access keys
    print("[2/2] Auditing IAM access keys...")
    iam_findings = audit_iam_access_keys()
    all_findings.extend(iam_findings)
    print(f"  Found {len(iam_findings)} keys used during attack window")
    print()

    # Categorize findings
    critical = [f for f in all_findings if f.get("risk") == "critical"]
    high = [f for f in all_findings if f.get("risk") == "high"]
    medium = [f for f in all_findings if f.get("risk") == "medium"]

    print("=" * 60)
    print("RESULTS")
    print("=" * 60)
    print(f"  Critical: {len(critical)}")
    print(f"  High:     {len(high)}")
    print(f"  Medium:   {len(medium)}")
    print(f"  Low:      {len(all_findings) - len(critical) - len(high) - len(medium)}")
    print()

    if critical:
        print("[CRITICAL FINDINGS]")
        for f in critical:
            print(f"  {f['timestamp']} | {f.get('event', f.get('type'))} | {f['reason']}")
        print()

    if high:
        print("[HIGH FINDINGS]")
        for f in high:
            print(f"  {f['timestamp']} | {f.get('event', f.get('type'))} | {f['reason']}")
        print()

    # Export full report
    report_path = f"aws_secrets_audit_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(report_path, "w") as fp:
        json.dump({"attack_window": {"start": ATTACK_WINDOW_START.isoformat(), "end": ATTACK_WINDOW_END.isoformat()}, "findings": all_findings}, fp, indent=2, default=str)
    print(f"Full report: {report_path}")

    if critical or high:
        print()
        print("RECOMMENDED ACTIONS:")
        print("  1. Rotate all secrets accessed during the attack window")
        print("  2. Revoke and recreate IAM access keys flagged above")
        print("  3. Review CloudTrail for lateral movement from flagged principals")
        print("  4. Enable AWS GuardDuty if not already active")


if __name__ == "__main__":
    main()
