#!/usr/bin/env bash
#
# container_image_audit.sh - Scan container registries for compromised Trivy images
#
# Checks Docker Hub, GHCR, and ECR for Trivy images tagged 0.69.4, 0.69.5, 0.69.6.
# Flags and provides quarantine commands for any compromised images found.
#
# Source: Wiz Research - Trivy/TeamPCP Supply Chain Attack (March 2026)
# Generated by KTLYST Security Learning Control Plane

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

COMPROMISED_TAGS=("0.69.4" "0.69.5" "0.69.6")
FINDINGS=0
REPORT_FILE="container_image_audit_$(date +%Y%m%d_%H%M%S).csv"

echo -e "${CYAN}=== Container Image Audit: Trivy Supply Chain ===${NC}"
echo "Scanning for compromised Trivy images (tags: 0.69.4, 0.69.5, 0.69.6)"
echo "Report: $REPORT_FILE"
echo ""

echo "registry,image,tag,status,action" > "$REPORT_FILE"

# --- Check 1: Local Docker images ---
echo -e "${CYAN}[1/4] Checking local Docker images...${NC}"

if command -v docker &>/dev/null; then
    for tag in "${COMPROMISED_TAGS[@]}"; do
        for repo in "aquasec/trivy" "ghcr.io/aquasecurity/trivy" "public.ecr.aws/aquasecurity/trivy"; do
            image="${repo}:${tag}"
            if docker image inspect "$image" &>/dev/null; then
                echo -e "  ${RED}[!] FOUND: $image${NC}"
                echo "local,$repo,$tag,COMPROMISED,docker rmi $image" >> "$REPORT_FILE"
                FINDINGS=$((FINDINGS + 1))
            fi
        done
    done

    # Check for any running containers with compromised images
    echo ""
    echo "  Checking running containers..."
    docker ps --format '{{.ID}}\t{{.Image}}\t{{.Status}}' 2>/dev/null | while IFS=$'\t' read -r id image status; do
        for tag in "${COMPROMISED_TAGS[@]}"; do
            if [[ "$image" == *"trivy"*"$tag"* ]]; then
                echo -e "  ${RED}[!] RUNNING CONTAINER: $id ($image) - $status${NC}"
                echo "local-running,$image,$tag,ACTIVE_COMPROMISED,docker stop $id && docker rm $id" >> "$REPORT_FILE"
                FINDINGS=$((FINDINGS + 1))
            fi
        done
    done

    # Check build history for images built with compromised Trivy
    echo ""
    echo "  Checking images built during attack window..."
    docker images --format '{{.Repository}}:{{.Tag}}\t{{.CreatedAt}}' 2>/dev/null | while IFS=$'\t' read -r image created; do
        if [[ "$created" > "2026-03-19" ]] && [[ "$created" < "2026-03-24" ]]; then
            echo -e "  ${YELLOW}[?] Image built during attack window: $image ($created)${NC}"
            echo "  Verify this image was not built using compromised Trivy scan."
        fi
    done
else
    echo -e "  ${YELLOW}Docker not available${NC}"
fi
echo ""

# --- Check 2: Docker Hub ---
echo -e "${CYAN}[2/4] Checking Docker Hub for pulled images...${NC}"

for tag in "${COMPROMISED_TAGS[@]}"; do
    echo "  Checking aquasec/trivy:$tag ..."
    # Use Docker Hub API to check if tag exists
    response=$(curl -s "https://hub.docker.com/v2/repositories/aquasec/trivy/tags/$tag" 2>/dev/null || echo '{"error":"timeout"}')
    if echo "$response" | grep -q '"name"'; then
        echo -e "  ${RED}[!] Tag $tag exists on Docker Hub (may have been cleaned up by now)${NC}"
        echo "dockerhub,aquasec/trivy,$tag,EXISTS_ON_REGISTRY,verify_and_avoid" >> "$REPORT_FILE"
    else
        echo -e "  ${GREEN}  Tag $tag not found (likely removed)${NC}"
    fi
done
echo ""

# --- Check 3: GitHub Container Registry (GHCR) ---
echo -e "${CYAN}[3/4] Checking GHCR...${NC}"

if command -v gh &>/dev/null; then
    for tag in "${COMPROMISED_TAGS[@]}"; do
        echo "  Checking ghcr.io/aquasecurity/trivy:$tag ..."
        result=$(gh api "/orgs/aquasecurity/packages/container/trivy/versions" --jq ".[] | select(.metadata.container.tags[] == \"$tag\") | .id" 2>/dev/null || echo "")
        if [ -n "$result" ]; then
            echo -e "  ${RED}[!] Tag $tag found on GHCR${NC}"
            echo "ghcr,aquasecurity/trivy,$tag,EXISTS_ON_REGISTRY,verify_and_avoid" >> "$REPORT_FILE"
        else
            echo -e "  ${GREEN}  Tag $tag not found on GHCR${NC}"
        fi
    done
else
    echo -e "  ${YELLOW}gh CLI not available - skipping GHCR check${NC}"
fi
echo ""

# --- Check 4: Amazon ECR ---
echo -e "${CYAN}[4/4] Checking Amazon ECR...${NC}"

if command -v aws &>/dev/null; then
    # Check ECR Public
    for tag in "${COMPROMISED_TAGS[@]}"; do
        echo "  Checking ECR public for trivy:$tag ..."
        result=$(aws ecr-public describe-images \
            --repository-name aquasecurity/trivy \
            --region us-east-1 \
            --image-ids imageTag="$tag" 2>/dev/null || echo "")
        if [ -n "$result" ] && echo "$result" | grep -q "imageDigest"; then
            echo -e "  ${RED}[!] Tag $tag found on ECR Public${NC}"
            echo "ecr-public,aquasecurity/trivy,$tag,EXISTS_ON_REGISTRY,verify_and_avoid" >> "$REPORT_FILE"
        else
            echo -e "  ${GREEN}  Tag $tag not found on ECR Public${NC}"
        fi
    done

    # Check private ECR repos in your account
    echo ""
    echo "  Checking private ECR repositories..."
    repos=$(aws ecr describe-repositories --query 'repositories[*].repositoryName' --output text 2>/dev/null || echo "")
    for repo in $repos; do
        if [[ "$repo" == *"trivy"* ]]; then
            for tag in "${COMPROMISED_TAGS[@]}"; do
                result=$(aws ecr describe-images --repository-name "$repo" --image-ids imageTag="$tag" 2>/dev/null || echo "")
                if [ -n "$result" ] && echo "$result" | grep -q "imageDigest"; then
                    echo -e "  ${RED}[!] PRIVATE ECR: $repo:$tag${NC}"
                    echo "ecr-private,$repo,$tag,COMPROMISED,aws ecr batch-delete-image --repository-name $repo --image-ids imageTag=$tag" >> "$REPORT_FILE"
                    FINDINGS=$((FINDINGS + 1))
                fi
            done
        fi
    done
else
    echo -e "  ${YELLOW}AWS CLI not available - skipping ECR check${NC}"
fi
echo ""

# --- Summary ---
echo -e "${CYAN}=== Audit Summary ===${NC}"
echo "Report written to: $REPORT_FILE"
if [ $FINDINGS -gt 0 ]; then
    echo -e "${RED}FINDINGS: $FINDINGS compromised images found locally${NC}"
    echo ""
    echo "Remediation:"
    echo "  1. Remove all compromised images immediately"
    echo "  2. Rebuild any production images that used Trivy 0.69.4/5/6 for scanning"
    echo "  3. Audit CI/CD pipelines for cached compromised images"
    echo "  4. Update Trivy to latest clean version"
else
    echo -e "${GREEN}No compromised Trivy images found in local registries${NC}"
fi
