# KTLYST - Block phishing domains via Exchange Online transport rule
# Generated: 2026-04-10
# Organization: Christiana Care Health System
# Review before running. This blocks inbound email containing these domains.
#
# Prerequisites:
#   Connect-ExchangeOnline -UserPrincipalName admin@yourdomain.com

$domains = @('')

New-TransportRule `
    -Name "Christiana Care Health System - KTLYST Block Phishing Domains (2026-04-10)" `
    -SubjectOrBodyContainsWords $domains `
    -FromAddressContainsWords $domains `
    -SenderDomainIs $domains `
    -DeleteMessage $true `
    -Comments "Auto-generated by KTLYST for Christiana Care Health System."

# To also block in URLs within message bodies:
# New-TransportRule `
#     -Name "Christiana Care Health System - KTLYST Block Phishing URLs (2026-04-10)" `
#     -HeaderContainsMessageHeader "X-MS-Exchange-Organization-UrlScan-Verdict" `
#     -SubjectOrBodyContainsWords $domains `
#     -DeleteMessage $true
